#!/bin/bash
# =============================================================================
# build.sh — convert official ReactiveX/RxSwift into DYNAMIC .xcframeworks
# =============================================================================
# Why: on Xcode 26/27 the iOS Simulator is arm64-only (Rosetta/x86_64 sims were
# removed). Consuming RxSwift as a *static* SwiftPM library then links a full
# copy of RxSwift into BOTH the app and its xctest bundle; two copies of
# RxSwift's Swift generic metadata in one process -> `getSuperclassMetadata`
# SIGABRT (SR-12303). Building each RxSwift module as its own *dynamic*
# framework (Carthage-style: RxCocoa.framework dynamically links
# RxSwift.framework via @rpath) means the whole process shares exactly ONE
# RxSwift — no duplication, no crash.
#
# This script is fully reproducible: it clones the official RxSwift at an exact
# tag, builds device + simulator (arm64 & x86_64) slices with library
# evolution, injects the upstream privacy manifests, assembles xcframeworks,
# zips them, computes SwiftPM checksums, and regenerates Package.swift. Re-run
# it with a new tag to update.
#
# Usage:   ./build.sh <rxswift-version> [github-owner/repo]
# Example: ./build.sh 6.7.0
# =============================================================================
set -euo pipefail

VERSION="${1:?usage: ./build.sh <rxswift-version> [owner/repo]}"
REPO="${2:-mdata-group/rxswift-dynamic-xcframework}"
# Release/download tag. Defaults to VERSION, but the prebuilt xcframeworks are
# tied to the Swift toolchain that produced their .swiftinterface, so a rebuild
# with a different Xcode must publish under a distinct tag (e.g. RELEASE_TAG=6.7.0-xcode26.2).
REL_TAG="${RELEASE_TAG:-$VERSION}"
MIN_IOS="${MIN_IOS:-15.0}"
MODULES=(RxSwift RxRelay RxCocoa RxTest RxBlocking)

ROOT="$(cd "$(dirname "$0")" && pwd)"
WORK="$ROOT/.build"
SRC="$WORK/RxSwift"
XCF="$ROOT/xcframeworks"
REL="$ROOT/release"

command -v xcodebuild >/dev/null || { echo "xcodebuild not found"; exit 1; }
echo "Xcode: $(xcodebuild -version | tr '\n' ' ')"
rm -rf "$WORK" "$XCF" "$REL"; mkdir -p "$WORK" "$XCF" "$REL"

echo "==> 1/5 clone ReactiveX/RxSwift @ $VERSION"
git clone --quiet --depth 1 --branch "$VERSION" https://github.com/ReactiveX/RxSwift "$SRC"

COMMON=(SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
        "IPHONEOS_DEPLOYMENT_TARGET=$MIN_IOS" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_ALLOWED=NO)

echo "==> 2/6 archive each module (device + simulator) as dynamic frameworks"
cd "$SRC"
for M in "${MODULES[@]}"; do
  echo "    - $M (iphoneos)"
  xcodebuild archive -project Rx.xcodeproj -scheme "$M" \
    -destination 'generic/platform=iOS' -archivePath "$WORK/$M-ios" "${COMMON[@]}" >/dev/null
  echo "    - $M (iphonesimulator)"
  xcodebuild archive -project Rx.xcodeproj -scheme "$M" \
    -destination 'generic/platform=iOS Simulator' -archivePath "$WORK/$M-sim" "${COMMON[@]}" >/dev/null
done

# RxSwift/RxCocoa are on Apple's list of commonly used third-party SDKs, so the
# consuming app has to ship their privacy manifests. Upstream (6.8.0+) declares
# them via SwiftPM `.copy("PrivacyInfo.xcprivacy")` under Sources/<module>/ —
# Rx.xcodeproj's targets never reference those files, so an xcodebuild archive
# drops them. Copy each manifest to its framework bundle root, which is where
# Apple's privacy report reads it from for a framework.
echo "==> 3/6 inject upstream PrivacyInfo.xcprivacy"
for M in "${MODULES[@]}"; do
  MANIFEST="$SRC/Sources/$M/PrivacyInfo.xcprivacy"
  if [ ! -f "$MANIFEST" ]; then
    echo "    - $M: none upstream, skipped"
    continue
  fi
  for SLICE in ios sim; do
    cp "$MANIFEST" "$WORK/$M-$SLICE.xcarchive/Products/Library/Frameworks/$M.framework/PrivacyInfo.xcprivacy"
  done
  echo "    - $M: injected (device + simulator)"
done

echo "==> 4/6 create xcframeworks"
for M in "${MODULES[@]}"; do
  xcodebuild -create-xcframework \
    -framework "$WORK/$M-ios.xcarchive/Products/Library/Frameworks/$M.framework" \
    -framework "$WORK/$M-sim.xcarchive/Products/Library/Frameworks/$M.framework" \
    -output "$XCF/$M.xcframework" >/dev/null
  echo "    - $M.xcframework: $(ls "$XCF/$M.xcframework" | grep -v Info.plist | tr '\n' ' ')"
done

echo "==> 5/6 zip + checksum"
# bash 3.2 (stock macOS) has no associative arrays; keep a "<module> <sha>" table.
SUMFILE="$WORK/checksums.txt"; : > "$SUMFILE"
for M in "${MODULES[@]}"; do
  ( cd "$XCF" && zip -rqy "$REL/$M.xcframework.zip" "$M.xcframework" )
  sum=$(swift package compute-checksum "$REL/$M.xcframework.zip")
  echo "$M $sum" >> "$SUMFILE"
  echo "    - $M.xcframework.zip  $sum"
done
sumfor() { awk -v m="$1" '$1==m{print $2}' "$SUMFILE"; }

echo "==> 6/6 generate Package.swift"
BASE="https://github.com/$REPO/releases/download/$REL_TAG"
{
  echo "// swift-tools-version: 5.9"
  echo "// AUTO-GENERATED by build.sh for RxSwift $VERSION. Do not edit by hand."
  echo "import PackageDescription"
  echo ""
  echo "let package = Package("
  echo "    name: \"RxSwiftDynamic\","
  echo "    platforms: [.iOS(\"$MIN_IOS\")],"
  echo "    products: ["
  for M in "${MODULES[@]}"; do echo "        .library(name: \"$M\", targets: [\"$M\"]),"; done
  echo "    ],"
  echo "    targets: ["
  for M in "${MODULES[@]}"; do
    echo "        .binaryTarget("
    echo "            name: \"$M\","
    echo "            url: \"$BASE/$M.xcframework.zip\","
    echo "            checksum: \"$(sumfor "$M")\"),"
  done
  echo "    ]"
  echo ")"
} > "$ROOT/Package.swift"

echo ""
echo "==> verify (each: device ios-arm64 + ios-arm64_x86_64-simulator; RxCocoa @rpath-links RxSwift)"
for M in "${MODULES[@]}"; do
  slices=$(ls "$XCF/$M.xcframework" | grep -v Info.plist | tr '\n' ' ')
  echo "    $M: $slices"
done
echo "    RxCocoa deps:"; otool -L "$XCF/RxCocoa.xcframework/ios-arm64/RxCocoa.framework/RxCocoa" | grep -oE "@rpath/Rx[A-Za-z]+\.framework" | sort -u | sed 's/^/      /'
echo "    privacy manifests:"
for M in "${MODULES[@]}"; do
  for SLICE in "$XCF/$M.xcframework"/*/; do
    [ -d "$SLICE$M.framework" ] || continue
    if [ -f "$SLICE$M.framework/PrivacyInfo.xcprivacy" ]; then STATE="present"; else STATE="ABSENT"; fi
    echo "      $M/$(basename "$SLICE"): $STATE"
  done
done

echo ""
echo "DONE. Next steps:"
echo "  git add build.sh README.md Package.swift LICENSE .gitignore"
echo "  git commit -m \"RxSwift $VERSION dynamic xcframeworks ($REL_TAG)\" && git tag $REL_TAG && git push --tags"
echo "  gh release create $REL_TAG release/*.xcframework.zip --title \"RxSwift $VERSION (dynamic xcframeworks, $REL_TAG)\""
