// swift-tools-version: 5.9
// AUTO-GENERATED by build.sh for RxSwift 6.8.0. Do not edit by hand.
import PackageDescription

let package = Package(
    name: "RxSwiftDynamic",
    platforms: [.iOS("15.0")],
    products: [
        .library(name: "RxSwift", targets: ["RxSwift"]),
        .library(name: "RxRelay", targets: ["RxRelay"]),
        .library(name: "RxCocoa", targets: ["RxCocoa"]),
        .library(name: "RxTest", targets: ["RxTest"]),
        .library(name: "RxBlocking", targets: ["RxBlocking"]),
    ],
    targets: [
        .binaryTarget(
            name: "RxSwift",
            url: "https://github.com/mdata-group/rxswift-dynamic-xcframework/releases/download/6.8.0-xcode26.2/RxSwift.xcframework.zip",
            checksum: "c4e329b30fd000edee09d394d68c74da6f2845df6740f163119a121e056a2d13"),
        .binaryTarget(
            name: "RxRelay",
            url: "https://github.com/mdata-group/rxswift-dynamic-xcframework/releases/download/6.8.0-xcode26.2/RxRelay.xcframework.zip",
            checksum: "95bc7bad0a307d668f327c15d00f6a05c9a68762b4c066c489f230b87f737551"),
        .binaryTarget(
            name: "RxCocoa",
            url: "https://github.com/mdata-group/rxswift-dynamic-xcframework/releases/download/6.8.0-xcode26.2/RxCocoa.xcframework.zip",
            checksum: "780ce3ed1e6875787e42fa82fa7ccd2099f496eeb1d85014b53bbb8fea03b674"),
        .binaryTarget(
            name: "RxTest",
            url: "https://github.com/mdata-group/rxswift-dynamic-xcframework/releases/download/6.8.0-xcode26.2/RxTest.xcframework.zip",
            checksum: "6d5cc1434c4b4065c22a99b326b683897904432a80eb4338ad70199a58771224"),
        .binaryTarget(
            name: "RxBlocking",
            url: "https://github.com/mdata-group/rxswift-dynamic-xcframework/releases/download/6.8.0-xcode26.2/RxBlocking.xcframework.zip",
            checksum: "d3bd2ec87b87a0bb3a212c6b01d6a650d203b5a6a2e9bd64886b2fd9c0cf8e89"),
    ]
)
