// swift-tools-version: 5.9
// AUTO-GENERATED by build.sh from the official RxSwift 6.9.1 xcframework release.
// Do not edit by hand.
import PackageDescription

let package = Package(
    name: "RxSwiftDynamic",
    platforms: [.iOS("15.0")],
    products: [
        .library(name: "RxSwift", targets: ["RxSwift"]),
        .library(name: "RxRelay", targets: ["RxRelay"]),
        .library(name: "RxCocoa", targets: ["RxCocoa"]),
        .library(name: "RxTest", targets: ["RxTest"]),
        .library(name: "RxBlocking", targets: ["RxBlocking"]),
    ],
    targets: [
        .binaryTarget(
            name: "RxSwift",
            url: "https://github.com/mdata-group/rxswift-dynamic-xcframework/releases/download/6.9.1/RxSwift.xcframework.zip",
            checksum: "4cac480b4b8825caab86b607b53c8576cf9f20e5854ca93cc27571ad91ec0275"),
        .binaryTarget(
            name: "RxRelay",
            url: "https://github.com/mdata-group/rxswift-dynamic-xcframework/releases/download/6.9.1/RxRelay.xcframework.zip",
            checksum: "72e5981828a30c88704244ddf55de3d7ce118e0359c61118fb265ef291e76e22"),
        .binaryTarget(
            name: "RxCocoa",
            url: "https://github.com/mdata-group/rxswift-dynamic-xcframework/releases/download/6.9.1/RxCocoa.xcframework.zip",
            checksum: "0d52ecfcd86080681666714c5b7cd0a0e2c9a46a100d98c5a7edf91d9ba9a9e3"),
        .binaryTarget(
            name: "RxTest",
            url: "https://github.com/mdata-group/rxswift-dynamic-xcframework/releases/download/6.9.1/RxTest.xcframework.zip",
            checksum: "7d612c52d8ebf7c77080ffc037abb05fb844ebb226faf421509c707695517ddc"),
        .binaryTarget(
            name: "RxBlocking",
            url: "https://github.com/mdata-group/rxswift-dynamic-xcframework/releases/download/6.9.1/RxBlocking.xcframework.zip",
            checksum: "d6d485496e268790284bc7a68ed9ffc8d57b3a3579168f807008c0aa4943aac6"),
    ]
)
